{% set name = "FrictionQPotFEM" %}
{% set version = "0.11.2" %}

package:
  name: python-{{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tdegeus/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 91d038546517b215fa1470a259331550069a40e33fb13f3b06838c5d9ee4a954

build:
  number: 0
  script_env: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - setuptools_scm
    - pip
    - pyxtensor
    - goosefem
    - gmattensor
    - gmatelastoplasticqpot
  run:
    - python

test:
  imports:
    - {{ name }}
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tdegeus/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Library to run friction simulations based on "GMatElastoPlasticQPot" and "GooseFEM".
  description: Library to run friction simulations based on "GMatElastoPlasticQPot" and "GooseFEM".
  doc_url: https://tdegeus.github.io/{{ name }}
  dev_url: https://github.com/tdegeus/{{ name }}

extra:
  recipe-maintainers:
    - tdegeus
